### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by Freso** [toolboc/musicbrainz-conversation-bot#2]
@toolboc said in the #musicbrainz IRC channel that the bot was [OSS](https://opensource.org/osd-annotated), but I don't see a [license](https://opensource.org/licenses) specified in the repository.

**Comment by toolboc** [comment]
Easy, we want to be simple and permissive, will make it official with an MIT license.

**Comment by toolboc** [comment]
Addressed in caad40b
